/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/router';


import {
  MyComponent as TodoList
} from './components/todo-list/todo-list';

declare global {
  interface HTMLTodoListElement extends TodoList, HTMLElement {
  }
  var HTMLTodoListElement: {
    prototype: HTMLTodoListElement;
    new (): HTMLTodoListElement;
  };
  interface HTMLElementTagNameMap {
    "todo-list": HTMLTodoListElement;
  }
  interface ElementTagNameMap {
    "todo-list": HTMLTodoListElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "todo-list": JSXElements.TodoListAttributes;
    }
  }
  namespace JSXElements {
    export interface TodoListAttributes extends HTMLAttributes {
      items?: any[];
    }
  }
}

